# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataScience_SpecialSlice_Dialog_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DSc_SelectSlice_Dialog(object):
    def setupUi(self, DSc_SelectSlice_Dialog):
        DSc_SelectSlice_Dialog.setObjectName("DSc_SelectSlice_Dialog")
        DSc_SelectSlice_Dialog.resize(346, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(DSc_SelectSlice_Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.DSc_SelectSlice_listWidget = QtWidgets.QListWidget(DSc_SelectSlice_Dialog)
        self.DSc_SelectSlice_listWidget.setObjectName("DSc_SelectSlice_listWidget")
        self.verticalLayout.addWidget(self.DSc_SelectSlice_listWidget)
        self.DSc_SelectSlice_buttonBox = QtWidgets.QDialogButtonBox(DSc_SelectSlice_Dialog)
        self.DSc_SelectSlice_buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.DSc_SelectSlice_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.DSc_SelectSlice_buttonBox.setObjectName("DSc_SelectSlice_buttonBox")
        self.verticalLayout.addWidget(self.DSc_SelectSlice_buttonBox)
        self.Selected_Slice_label = QtWidgets.QLabel(DSc_SelectSlice_Dialog)
        self.Selected_Slice_label.setObjectName("Selected_Slice_label")
        self.verticalLayout.addWidget(self.Selected_Slice_label)

        self.retranslateUi(DSc_SelectSlice_Dialog)
        self.DSc_SelectSlice_buttonBox.accepted.connect(DSc_SelectSlice_Dialog.accept)
        self.DSc_SelectSlice_buttonBox.rejected.connect(DSc_SelectSlice_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(DSc_SelectSlice_Dialog)

    def retranslateUi(self, DSc_SelectSlice_Dialog):
        _translate = QtCore.QCoreApplication.translate
        DSc_SelectSlice_Dialog.setWindowTitle(_translate("DSc_SelectSlice_Dialog", "Dialog"))
        self.Selected_Slice_label.setText(_translate("DSc_SelectSlice_Dialog", "Selected item..."))
