# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SpecDecompTool_Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpecDecomTool_Main(object):
    def setupUi(self, SpecDecomTool_Main):
        SpecDecomTool_Main.setObjectName("SpecDecomTool_Main")
        SpecDecomTool_Main.resize(604, 755)
        self.centralwidget = QtWidgets.QWidget(SpecDecomTool_Main)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 580, 680))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(190, 40, 171, 91))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        SpecDecomTool_Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SpecDecomTool_Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 604, 26))
        self.menubar.setObjectName("menubar")
        SpecDecomTool_Main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SpecDecomTool_Main)
        self.statusbar.setObjectName("statusbar")
        SpecDecomTool_Main.setStatusBar(self.statusbar)

        self.retranslateUi(SpecDecomTool_Main)
        QtCore.QMetaObject.connectSlotsByName(SpecDecomTool_Main)

    def retranslateUi(self, SpecDecomTool_Main):
        _translate = QtCore.QCoreApplication.translate
        SpecDecomTool_Main.setWindowTitle(_translate("SpecDecomTool_Main", "Spectral Decomposition Tool"))
        self.label.setText(_translate("SpecDecomTool_Main", "I will start here:"))
